spring:
  datasource:
    url: jdbc:mysql://db.mysql.cmyserver.com:19003/api_neighborhood
    username: test_root
    password: Iancomaya1208
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 885572470281-qf7dm2q3lq1u61tmvlhmb7pnfccv3rdn.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope: email,profile
          facebook:
            client-id: 3286194728358778
            client-secret: eb2c8c50208effc8c2f805e6a0aba94f
            redirect-uri: http://localhost:8080/oauth2/callback/facebook
            scope: email,public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=name,email,picture.width(250).height(250)
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
            tokenUri: https://www.googleapis.com/oauth2/v4/token
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

app:
  auth:
    tokenSecret: f35c111daf4a1f48a0629daccdd11faa25709c5ad0a473f914f6120f9bb52323
    tokenExpireMs: 864000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    authorizedRedirectUris:
      - http://127.0.0.1:5173/oauth2/redirect
